# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
target 'TestYoutube' do
  use_frameworks!
  pod 'youtube-ios-player-helper', '~> 0.1.4'
end
